CREATE SCHEMA proyectointegrador;

CREATE TABLE productos(
	id INT UNSIGNED PRIMARY KEY auto_increment,
    nombr_imagen INT NOT NULL,
    nombre VARCHAR(100),
    descripcion VARCHAR(100) NOT NULL,
    
    createdAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deletedAT TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP

);

CREATE TABLE comentarios(
	id INT PRIMARY KEY auto_increment,
    usuario VARCHAR(100) NOT NULL,
    texto VARCHAR(100) NOT NULL,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	deletedAt TIMESTAMP NULL ON UPDATE CURRENT_TIMESTAMP 
);

















